### PR TITLE
fix: fix progress window for 'minikube start'

### LINKED ISSUE #73: when click on start it the status should show Starting ...
when I right click on the try icon (and it is stoped) if I click on start I expect it to show Starting ... instead of Stoped in the tray icon

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
FIX #73 
feat: set status to starting when starting minikube

When minikube is being started (by minikube-gui), both the system tray and the main window will show status "Starting"

Like this:

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
@ComradeProgrammer thank you for this PR, 

can we make it that, if "minikube start" fails, will it revert back to what the status was before?

to test it you can start minikube with Gui, and then Kill the minikube in terminal, and u should expect some failure...and it should no longer say starting..

to test it

**Comment by ComradeProgrammer** [comment]
I am indeed always ambitious, but this feature is definitely not a good place to be ambitious(laugh, it is a joke).

After reading the code I just found that Steven has previously implemented a more complicated progress tracking window like this:

Screenshot from 2023-06-25 22-39-37

When the minikube cluster is starting, real time outputs generated by `-o json` are sent to this window by `CommandRunner::output` signal, which is connected with `Operator::commandOutput`. After that, `Operator::commandOutput` updates the text and progress bar of this window.

However, this window, which had already implemented the required feature, was not visible at all before. It is because that when this window was created , the WindowFlags was incorrectly set.  It should be `Qt::Dialog| Qt::FramelessWindowHint` (which equals to `m_dialog->windowFlags() | Qt::FramelessWindowHint` in this PR), not solely `Qt::FramelessWindowHint`, which make this window disappear.

I just amended my PR and fixed this bug.

By the way, I am always looking forward to contributing to some more complicated features, if possible.  :)

**Comment by medyagh** [comment]
> I am indeed always ambitious, but this feature is definitely not a good place to be ambitious(laugh, it is a joke).
> 
> After reading the code I just found that Steven has previously implemented a more complicated progress tracking window like this:
> 
> Screenshot from 2023-06-25 22-39-37
> 
> When the minikube cluster is starting, real time outputs generated by `-o json` are sent to this window by `CommandRunner::output` signal, which is connected with `Operator::commandOutput`. After that, `Operator::commandOutput` updates the text and progress bar of this window.
> 
> However, this window, which had already implemented the required feature, was not visible at all before. It was because that when this window was created , the WindowFlags was incorrectly set. It should be `Qt::Dialog| Qt::FramelessWindowHint` (which equals to `m_dialog->windowFlags() | Qt::FramelessWindowHint` in this PR), not solely `Qt::FramelessWindowHint`, which make this window disappear.
> 
> I just amended my PR and fixed this bug.
> 
> By the way, I am always looking forward to contributing to some more complicated features, if possible. :)
> 
> @medyagh @spowelljr

Excellent ! @ComradeProgrammer good work here ! I appreciate your contribution and look forward to find good issues for you to work on

**Review by medyagh — APPROVED** [review]

File: src/operator.cpp [hunk 1]
```diff
@@ -151,7 +151,6 @@ void Operator::createCluster(QStringList args)
 
 void Operator::startCommandStarting()
 {
-    commandStarting();
```
Comment (spowelljr) [inline src/operator.cpp:154]: This doesn't fix it for me, for me, on main or this PR I get the same result. The start window shows up on the first start, but any subsequent starts the loading window doesn't show up.

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: src/operator.cpp (hunk 1 above)
Comment (spowelljr) [reply src/operator.cpp:154]: Fixed with https://github.com/kubernetes-sigs/minikube-gui/pull/86, could you revert removing this line and then it'll be good to merge

**Comment by spowelljr** [comment]
Thanks for fixing the progress loading bar!

However, for the status showing `Starting` I don't quite understand the change.

You're not manually setting the text to `Starting` and `minikube profile list -o json` doesn't get called until after the start command has completed, so how is the text becoming `Starting`?

**Comment by ComradeProgrammer** [comment]
> Thanks for fixing the progress loading bar!
> 
> However, for the status showing `Starting` I don't quite understand the change.
> 
> You're not manually setting the text to `Starting` and `minikube profile list -o json` doesn't get called until after the start command has completed, so how is the text becoming `Starting`?

Oh sorry I removed that part of code.

On the one hand, perhaps with this progress bar blocking the main window, we no longer need to change this text to make user understand minikube is being started.

On the other hand, because "Running" is not a status returned from minikube, so changing this text is quite complicated (we have to consider how to change the text back if this `minikube start ` command fails)

I have changed the picture, which no longer shows a "Running status"

**Review by medyagh — APPROVED** [review]
